Repository zbycz/osmapp, pull requests merged in 2023-06, with the labels that each got.

#158 Fix: Potential trail zoom issue fix
  src/components/Map/styles/outdoorStyle.ts
Labels: map-style

#154 layers: Add attribution to layers
  .gitignore
  src/components/LayerSwitcher/osmappLayers.tsx
  src/components/Map/MapFooter/MapFooter.tsx
  src/components/Map/MapFooter/MaptilerLogo.tsx
  src/components/utils/MapStateContext.tsx
  src/locales/vocabulary.js
Labels: ui

#155 layers: Add bing satellite
  src/components/LayerSwitcher/osmappLayers.tsx
  src/components/Map/behaviour/useUpdateStyle.tsx
  src/components/Map/styles/rasterStyle.ts
  src/components/utils/MapStateContext.tsx
  src/locales/am.js
  src/locales/cs.js
  src/locales/de.js
  src/locales/es.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/pl.js
  src/locales/vocabulary.js
Labels: enahcement

#131 iD Tagging scheme exploration
  package.json
  src/components/FeaturePanel/FeaturePanel.tsx
  src/components/FeaturePanel/FeaturedTags.tsx
  src/components/FeaturePanel/IdSchemeFields.tsx
  src/components/FeaturePanel/ImageSection/ImageSection.tsx
  src/components/FeaturePanel/ImageSection/PoiDescription.tsx
  src/components/utils/FeatureContext.tsx
  src/helpers/featureLabel.ts
  src/services/__tests__/osmApi.test.ts
  src/services/fetchCache.ts
  src/services/helpers.ts
  src/services/intl.tsx
  src/services/osmApi.ts
  src/services/tagging/__tests__/idTaggingScheme.test.ts
  src/services/tagging/data.ts
  src/services/tagging/fields.ts
  src/services/tagging/idTaggingScheme.ts
  src/services/tagging/presets.ts
  src/services/tagging/translations.ts
  src/services/tagging/types/Fields.ts
  src/services/tagging/types/Presets.ts
  src/services/types.ts
  src/utils.ts
  yarn.lock
Labels: new feature

#161 FeaturePanel: Add operator dropdown and hiding editor tags
  src/components/FeaturePanel/TagsTable.tsx
Labels: enahcement
